"""
Task 2 - AI Agent using LangChain and OpenAI API
=================================================

This AI agent analyzes user input and generates intelligent responses.
It includes:
- Conversational AI with OpenAI
- Multiple tools (calculator, knowledge base, time, text analyzer)
- Simple tool-based agent
"""

import os
from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage, SystemMessage
from datetime import datetime
import re
import json
from typing import Optional


class AIAgent:
    """
    A simple AI agent that can:
    1. Answer general questions
    2. Perform calculations
    3. Access a knowledge base
    4. Use multiple tools
    """
    def __init__(self, api_key: Optional[str] = None, model: str = "gpt-3.5-turbo"):
        """
        Initialize the AI agent with OpenAI API
        
        Args:
            api_key: OpenAI API key (or set OPENAI_API_KEY environment variable)
            model: OpenAI model to use
        """
        # Set API key
        if api_key:
            os.environ["OPENAI_API_KEY"] = api_key
        elif not os.environ.get("OPENAI_API_KEY"):
            raise ValueError("OpenAI API key not provided. Set OPENAI_API_KEY environment variable or pass api_key parameter.")
        
        # Initialize LLM
        self.llm = ChatOpenAI(temperature=0.7, model=model)
        
        # Tool definitions
        self.tools = {
            "calculator": self.calculator,
            "knowledge_base": self.knowledge_base,
            "get_current_time": self.get_current_time,
            "text_analyzer": self.text_analyzer
        }
        
        print(f"✓ AI Agent initialized successfully with model: {model}")
        print(f"✓ Available tools: {', '.join(self.tools.keys())}")
    
    def calculator(self, expression: str) -> str:
        """Evaluate mathematical expressions."""
        try:
            # Basic safety: only allow numbers and operators
            if re.match(r'^[\d\s\+\-\*/\(\)\.]+$', expression):
                result = eval(expression)
                return f"The result is: {result}"
            else:
                return "Invalid expression. Only use numbers and operators (+, -, *, /, parentheses)."
        except Exception as e:
            return f"Error calculating: {str(e)}"
    
    def knowledge_base(self, query: str) -> str:
        """Search the knowledge base for information."""
        knowledge = {
            "siem": "SIEM (Security Information and Event Management) is a security solution that provides real-time analysis of security alerts generated by applications and network hardware. It combines Security Information Management (SIM) and Security Event Management (SEM) to provide comprehensive visibility into an organization's IT security.",
            "machine learning": "Machine Learning is a subset of artificial intelligence that enables systems to learn and improve from experience without being explicitly programmed. It uses algorithms to parse data, learn from it, and make predictions or decisions.",
            "intrusion detection": "Intrusion Detection Systems (IDS) monitor network traffic for suspicious activity and known threats, sending alerts when potential security breaches are detected. They can be signature-based or anomaly-based.",
            "random forest": "Random Forest is an ensemble learning method that constructs multiple decision trees during training and outputs the mode of classes (classification) or mean prediction (regression) of individual trees. It's robust and handles overfitting well.",
            "langchain": "LangChain is a framework for developing applications powered by language models. It provides tools for chaining prompts, agents, memory, and integrations with various APIs and databases.",
        }
        
        query_lower = query.lower()
        for key, value in knowledge.items():
            if key in query_lower:
                return value
        
        return "I don't have specific information about that topic in my knowledge base. Try asking about: SIEM, Machine Learning, Intrusion Detection, Random Forest, or LangChain."
    
    def get_current_time(self, _: str = "") -> str:
        """Get the current date and time."""
        now = datetime.now()
        return f"Current date and time: {now.strftime('%Y-%m-%d %H:%M:%S')}"
    
    def text_analyzer(self, text: str) -> str:
        """Analyze text and provide statistics."""
        words = len(text.split())
        chars = len(text)
        sentences = len([s for s in text.split('.') if s.strip()])
        
        return f"Text Analysis:\n- Words: {words}\n- Characters: {chars}\n- Sentences: {sentences}"
    
    def chat(self, user_input: str) -> str:
        """
        Send a message to the agent and get a response
        
        Args:
            user_input: The user's message/question
            
        Returns:
            The agent's response
        """
        try:
            user_lower = user_input.lower()
            
            # First, check if we should use a specific tool
            tool_result = None
            
            # Check for calculation requests
            if any(keyword in user_lower for keyword in ["calculate", "compute", "solve"]) or \
               re.search(r'\d+\s*[\+\-\*/]\s*\d+', user_input):
                # Extract mathematical expression
                expression = re.search(r'[\d\s\+\-\*/\(\)\.]+', user_input)
                if expression:
                    tool_result = self.calculator(expression.group())
            
            # Check for time/date requests
            elif any(keyword in user_lower for keyword in ["time", "date", "today", "now", "current time"]):
                tool_result = self.get_current_time()
            
            # Check for text analysis requests
            elif "analyze" in user_lower and "text" in user_lower:
                match = re.search(r'["\'](.+?)["\']', user_input)
                if match:
                    tool_result = self.text_analyzer(match.group(1))
            
            # Check knowledge base for specific topics
            elif any(topic in user_lower for topic in ["siem", "machine learning", "intrusion detection", "random forest", "langchain"]):
                kb_result = self.knowledge_base(user_input)
                if "don't have specific information" not in kb_result:
                    tool_result = kb_result
            
            # If a tool was used, combine with LLM for natural response
            if tool_result:
                messages = [
                    SystemMessage(content="You are a helpful AI assistant. The tool has provided this information. Use it to give a complete, natural answer to the user."),
                    HumanMessage(content=f"User asked: {user_input}\n\nTool result: {tool_result}\n\nProvide a helpful response.")
                ]
                response = self.llm.invoke(messages)
                content = response.content
                if isinstance(content, list):
                    return str(content)
                return content
            
            # Otherwise, use LLM directly for ANY question - general conversation
            messages = [
                SystemMessage(content="""You are a helpful, knowledgeable AI assistant. 
                You can answer questions on ANY topic, have conversations, provide explanations, 
                give advice, write code, help with tasks, and engage in discussions. 
                Be friendly, clear, informative, and conversational.
                
                You also have access to these specialized tools when needed:
                - Calculator for math operations
                - Knowledge base for cybersecurity and ML topics  
                - Current time/date information
                - Text analysis capabilities
                
                Answer naturally and helpfully, regardless of the topic."""),
                HumanMessage(content=user_input)
            ]
            
            response = self.llm.invoke(messages)
            # Handle response.content which can be str or list
            content = response.content
            if isinstance(content, list):
                return str(content)
            return content
            
        except Exception as e:
            return f"Error: {str(e)}"


def main():
    """
    Main function to demonstrate the AI agent
    """
    print("="*70)
    print("Task 2 - AI Agent Demo (LangChain + OpenAI)")
    print("="*70)
    
    # Check for API key
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        print("\n⚠ WARNING: OPENAI_API_KEY not found in environment variables!")
        print("Please set your API key:")
        print("  Option 1: Set environment variable: $env:OPENAI_API_KEY='your-key-here'")
        print("  Option 2: Pass to AIAgent(api_key='your-key-here')")
        print("\nFor demo purposes, showing architecture...\n")
        
        # Demo mode without actual API
        demo_without_api()
        return
    
    try:
        # Initialize agent
        agent = AIAgent()
        
        # Demo conversations
        print("\n" + "="*70)
        print("DEMO CONVERSATIONS")
        print("="*70)
        
        # Example 1: General question
        print("\n[Example 1: General Question]")
        print("User: What is SIEM?")
        response = agent.chat("What is SIEM?")
        print(f"Agent: {response}")
        
        # Example 2: Calculator
        print("\n" + "-"*70)
        print("\n[Example 2: Calculation]")
        print("User: Calculate 156 * 24 + 89")
        response = agent.chat("Calculate 156 * 24 + 89")
        print(f"Agent: {response}")
        
        # Example 3: Current time
        print("\n" + "-"*70)
        print("\n[Example 3: Current Time]")
        print("User: What time is it?")
        response = agent.chat("What time is it?")
        print(f"Agent: {response}")
        
        # Interactive mode
        print("\n" + "="*70)
        print("INTERACTIVE MODE (type 'quit' to exit)")
        print("="*70)
        
        while True:
            user_input = input("\nYou: ").strip()
            
            if user_input.lower() in ['quit', 'exit', 'bye']:
                print("\n👋 Goodbye! Thank you for using the AI Agent.")
                break
            
            if not user_input:
                continue
            
            response = agent.chat(user_input)
            print(f"\n🤖 Agent: {response}")
    
    except Exception as e:
        print(f"\n❌ Error initializing agent: {str(e)}")
        print("\nMake sure you have:")
        print("1. Set OPENAI_API_KEY environment variable")
        print("2. Installed required packages: pip install -r requirements.txt")


def demo_without_api():
    """Demo mode that shows the structure without API calls"""
    print("\n📚 AI Agent Architecture:")
    print("\n1. LLM: ChatGPT (gpt-3.5-turbo)")
    print("2. Framework: LangChain")
    print("3. Tool System: Rule-based tool selection + LLM fallback")
    print("\n4. Available Tools:")
    print("   - Calculator: Perform math operations")
    print("   - KnowledgeBase: Answer cybersecurity/ML questions")
    print("   - CurrentTime: Get current date/time")
    print("   - TextAnalyzer: Analyze text statistics")
    
    print("\n5. Example Capabilities:")
    print("   ✓ Answer questions using knowledge base")
    print("   ✓ Perform calculations")
    print("   ✓ Get current time")
    print("   ✓ Analyze text statistics")
    print("   ✓ Use LLM for general conversation")
    
    print("\n6. Sample Interactions:")
    
    samples = [
        ("What is machine learning?", "Uses KnowledgeBase tool"),
        ("Calculate 25 * 48", "Uses Calculator tool → Result: 1200"),
        ("What time is it?", "Uses CurrentTime tool"),
        ("Analyze this text: 'Hello world'", "Uses TextAnalyzer for statistics")
    ]
    
    for query, expected in samples:
        print(f"\n   User: {query}")
        print(f"   Agent: {expected}")
    
    print("\n" + "="*70)
    print("To use the full agent, set OPENAI_API_KEY and run again.")
    print("="*70)


if __name__ == "__main__":
    main()
